name: Publish Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/build-and-pack

      - name: Publish beta
        if: contains(github.ref_name, 'beta')
        working-directory: staging/package
        run: npm publish --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish latest
        if: ${{ !contains(github.ref_name, 'beta') }}
        working-directory: staging/package
        run: npm publish --tag latest --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
